# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attends', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='NA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(default='NA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_mob', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_mob', models.CharField(max_length=15)),
                ('sms_mob', models.CharField(default=None, max_length=12)),
                ('school', models.CharField(max_length=100)),
                ('total_fees', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='student.batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.board'),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.standard'),
        ),
        migrations.AddField(
            model_name='attends',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_info'),
        ),
    ]
