# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 22:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attends',
            name='attendance_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='board',
            name='board',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='standard',
            name='standard',
            field=models.CharField(max_length=10),
        ),
    ]
