# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20160526_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='attends',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.batch'),
        ),
    ]
